spring:
  redis:
    database: 0
    host: 47.101.10.100
    port: 6379
    password: jackbin91
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000ms

  datasource:
    url: jdbc:mysql://39.100.117.228:3306/myDB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&connectTimeout=3000&socketTimeout=1000
    username: root
    password: Jackbin91**
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 5
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: stat # ,wall,log4j # \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1\uFF0C'wall'\u7528\u4E8E\u9632\u706B\u5899
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # \u901A\u8FC7connectProperties\u5C5E\u6027\u6765\u6253\u5F00mergeSql\u529F\u80FD\uFF1B\u6162SQL\u8BB0\u5F55
    useGlobalDataSourceStat: true # \u5408\u5E76\u591A\u4E2ADruidDataSource\u7684\u76D1\u63A7\u6570\u636E
    druidLoginName: yangbin1 # \u767B\u5F55druid\u7684\u8D26\u53F7
    druidPassword: jackbin91 # \u767B\u5F55druid\u7684\u5BC6\u7801
    cachePrepStmts: true  # \u5F00\u542F\u4E8C\u7EA7\u7F13\u5B58s

logging:
  config: classpath:logback-spring.xml
  path: /data/java/weblog/8082


server:
  port: 8082


mybatis:
  typeAliasesPackage: com.example.bootredis.mapper
  mapperLocations: classpath:/com/example/bootredis/mapper/*.xml
  mapperScanPackage: com.example.bootredis.mapper
  configLocation: classpath:/mybatis-config.xml